# Generated by Django 3.1.4 on 2020-12-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('EmpId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.employee')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('designation', models.CharField(choices=[('EXE', 'Executive'), ('SR_MGR', 'Senior manager'), ('MGR', 'Manager'), ('SR_ENG', 'Senior Engineer'), ('ENG', 'Engineer'), ('MCM', 'Master Craftsman'), ('GET', 'Graduate Engineer Trainee'), ('DET', 'Diploma Engineer Trainee'), ('OJT', 'On Job Trainee')], max_length=50)),
                ('section', models.CharField(choices=[('ADM', 'Administration'), ('PRO', 'Production'), ('TRG', 'Training')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='ProfilePics')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(verbose_name='')),
                ('status', models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('HF', 'Half Day'), ('L', 'Leave')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
