# Generated by Django 3.1.4 on 2021-01-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210101_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFaceData',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.employee')),
                ('embeddings', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employeeattendence',
            name='date',
            field=models.DateField(),
        ),
    ]
