# Generated by Django 3.1.4 on 2021-01-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210103_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAttendence',
        ),
    ]
