# Generated by Django 3.1.4 on 2021-01-09 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_employeeattendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefacedata',
            name='embeddings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
